import { workSans } from '@/utils/fonts';
import { theme } from '@/utils/theme';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const { currentTheme } = theme();

  return (
    <html lang="en">
      <body className={`${workSans.className} ${currentTheme}`}>
        {children}
      </body>
    </html>
  );
}
